### ISSUE TITLE
Scrolling progress should be persisted

### ISSUE THREAD

**Issue by sindresorhus** [metafizzy/infinite-scroll#337]
http://eviltrout.com/2013/02/16/infinite-scrolling-that-works.html

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports this feature. v3 manipulates browser URL and history via HTML5 `history` API. See [`history` option](https://infinite-scroll.com/options.html#history). Now you can scroll a couple pages, visit a different link, hit back, and you'll be back at the same page. Additionally I've added behavior so that the scroll position should be maintained (although it can be off due to first and subsequent pages having different page layouts).

[Try out Infinite Scroll v3 full page demo](https://infinite-scroll.com/demo/full-page/)

I recommend upgrading to v3. Thanks all for the input over the years. I'm delighted to finally ship this one. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
