### ISSUE TITLE
custom loading /  finished functions for memory issues

### ISSUE THREAD

**Issue by LOL2011** [metafizzy/infinite-scroll#491]
I want to use custom functions when the next page is loading and when the maxPage limit is reached.  

My scrolling could go on for pages and pages until the browser crashes due to memory issues,  I therefore need to stop infinite scrolling when the current page gets to maxPage and allow the user to select a "Load More" button.  Hopefully solving memory issues.

This is discussed in the link below but I cannot find any further documentation on how to do this exactly and can't even get the below sample to work.

https://github.com/paulirish/infinite-scroll/issues/300

I have tried the below based on the documentation, however this starts the loading function but doesn't ever call the finished function.  Its not calling the next page either when I look in the console.  What am I missing?

```
    // Infinite Ajax Scroll configuration
    $container.infinitescroll({
        navSelector: "div.paginate",
        nextSelector: "div.paginate a",
        itemSelector: "div.element",
        maxPage: 5,
        loading: {
            start: function(){
                  alert('started');

            },
            finished: function(){
                  alert('ended');

            }
        }
    },
    function(newElements) {

        var $newElements = $(newElements).css({opacity: 0});
        //remove the first item
        $newElements.splice(0, 1);

            $container.isotope('appended', $newElements);

        }

    });
});
```

**Comment by desandro** [comment]
Thanks fore reporting this issue. 

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 has events instead of `loading.start` and `loading.finished` option methods. See [`request`, `append`, and `load` events](https://infinite-scroll.com/events.html).

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
