### ISSUE TITLE
Plugin should support a request of type 'script' 

### ISSUE THREAD

**Issue by rschooley** [metafizzy/infinite-scroll#507]
This should be consistent with jquery dataType: script.

This is specifically needed to get Rails to render a .js view (Processing foo as JS)

**Comment by desandro** [comment]
[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll v3 supports loading text content by setting [`responseType: 'text'`](https://infinite-scroll.com/options.html#responsetype). Otherwise, if you want to load the response as JavaScript, Infinite Scroll v3 does not support that feature.

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3. 🌈🐻
