### ISSUE TITLE
Is there a way to auto trigger

### ISSUE THREAD

**Issue by iamloganmyers** [metafizzy/infinite-scroll#609]
???
without having to scroll to trigger, 
preferably it would be triggered on page load to load the next page

**Comment by iamloganmyers** [comment]
http://aimeegauthierdemo.tumblr.com/ (if you want to see a live demo)

The issue I am running into is that on a larger displays (ones that have a height greater than the content) there is no way to trigger the content to pull more... I was wondering if there was a way to auto trigger on page load? In the same sense that jscroll (https://github.com/pklauzinski/jscroll) allows

thank you for any help

**Comment by desandro** [comment]
Sorry to hear you're having trouble with Infinite Scroll.

[Infinite Scroll v3 is out!](https://infinite-scroll.com). It's an all new re-write, so take a look at [how to upgrade from v2](https://infinite-scroll.com/extras.html#upgrading-from-v2).

Infinite Scroll has a [`prefill` option](https://infinite-scroll.com/options.html#prefill) to keep loading content until the scroll requirement is met. Otherwise, you can manually trigger loading the next page with [`loadNextPage` method](https://infinite-scroll.com/api.html#loadnextpage)

I recommend upgrading to v3. Please open a new issue if you run into trouble with Infinite Scroll v3.
