### ISSUE TITLE
Issue with initial Isotope layout

### ISSUE THREAD

**Issue by macsupport** [metafizzy/infinite-scroll#677]
Playing with infinitescroll and Masonry/isotope, I have noticed an issue (other than the initial image overlap already reported). Masonry works well but I've found that if I use isotope.js instead of masonry.js , but initialize the grid with masonry code ( a coding accident) , [it still works](https://codepen.io/macsupport/pen/jwYKYo) (!) but if I use  isotope.js  and [initialize isotope as one should](https://codepen.io/macsupport/pen/gRoKvK), the masonry layout does not layout properly until the grid is resized, as if imagesloaded  is not present, i.e., it loads in one column initially
(Not sure how masonry initialization works with isotope.js ?) 

Mike
@jquerymac

**Comment by desandro** [comment]
Thanks for reporting this issue. 

1. "It still works" because `isotope.pkgd.js` includes everything in `masonry.pkgd.js`. Isotope is a superset of Masonry.
2. When using the [Masonry layout mode with Isotope](https://isotope.metafizzy.co/layout-modes/masonry.html), Masonry options `columnWidth` and `gutter` need to be set in a `masonry` object (this allows various layout modes to have similar option names but not overwrite one another).

``` js
 var $grid =  $('.grid').isotope({
  itemSelector: '.photo-item',
  masonry: {
    columnWidth: '.grid__col-sizer',
    gutter: '.grid__gutter-sizer',
  },
})
```

See demo https://codepen.io/desandro/pen/e9cb00062329d59e0fff54db7915d46d/

**Comment by macsupport** [comment]
Thanks. Darn,  I knew that about isotope but had a brain fart!
