### ISSUE TITLE
Feature: ES6

### ISSUE THREAD

**Issue by marcobiedermann** [metafizzy/infinite-scroll#680]
Hey David,
thank you very much for your great library.
How about switching to ES6 syntax? This would make the code way more easier to read and to maintain.
I suggest the following features:
* `import`, `export` statements
* `class` declaration
* `const`, `let` for variables
* `template strings` for class names

I would also create some extra wrappers for AMD, CommonJS and jQuery which allows all options without shipping unnecessary code.
ES6 `import` statements would allow to use tree shaking with e.g. rollup to reduce the filesize over all if some features are not needed.
If you like I could help you with some of these implementations. I am very open to hear you opinion on this one.

**Comment by desandro** [comment]
Hi! Thanks for this issue.

Officially, Infinite Scroll v3 supports IE 11. It's current market share is 3.5% globally, 6% in the US. When it drops to close to 1% (maybe in 1.5-2 years), I'll start looking at a major v4 update to start using ES6 features.

---

On this note, I don't see adopting ES6 as a big step forward for browser-based JS like Metafizzy libraries. There are some clearly great features (template strings, arrow functions instead of `.bind( this )`). But otherwise, implementing ES6 would clean up some code, at some complexity.

Consider that in order to implement a feature like `import`, it would require transpiling the codebase. Whereas right now I can easily debug the actual source code by running it directly in any browser. That direct application makes it the code so accessible. Not only can I debug it easier, but other users have that same access without having to know anything about its build process. I value that accessibility a lot.

So I'm open to it down the road. But for now, Infinite Scroll v3 is ES5. I'm closing this issue, but I appreciate getting the conversation started. ES6 will come soon enough!

**Comment by marcobiedermann** [comment]
@desandro Thank you David for your feeback.
I absolutely get your optionion, I had the same thought a couple of times before.
At the current state of browser support I would use a transpiler like babel to make sure the code is compatible with older browsers which only support ES5. Yes this would make the overall filesize a bit bigger but won't have that much impact if you are using some more libraries which use ES6 as well.

Fortunately modern browsers do support `import` on `<script type="module"></script>` which allows you to easily debug your source code in the browser. For all other browsers you could use sourcemaps to get a reference from your compiled code to your source code.

My prefered way to use technology is using the latest features and include a shim for older browsers. This way your code will always be ahead of time and modern browsers which so support newer features will benefit from that.

If you are changing your plan in the future, feel free to hit me up and I will help you as best as I can.
Cheers
