### ISSUE TITLE
Append event does not trigger when loading JSON

### ISSUE THREAD

**Issue by natehsu** [metafizzy/infinite-scroll#720]
Hi,
I try to add a append event, but the event does not trigger.
Have anyone a solution for this?

test case fork from Loading JSON example:
https://codepen.io/anon/pen/XeXrPM

Regards,
Nate

**Comment by desandro** [comment]
Hello! Thanks for reporting this issue. This is the expected behavior. The `append` event is only triggered as part of Infinite Scroll's load page behavior. It is not triggered when you use `appendItems`.

If this behavior is problematic for you, could you explain what you're trying to achieve? There may be another solution.

**Comment by natehsu** [comment]
Thank you for your feedback. 
I rewrite the code after `$container.infiniteScroll( 'appendItems', $items )` , and it works.
