### ISSUE TITLE
TypeError: instance._init is not a function

### ISSUE THREAD

**Issue by Xindi-Li** [metafizzy/infinite-scroll#743]
I want to add infinite scrolling on a table in a rails and react project. Here is what I did: I set tbody as container.
```
<tbody className="scroll">

          {_rows}

</tbody>
```
And then followed the steps in https://github.com/metafizzy/infinite-scroll/issues/673. `_rows` is an array containing some react tr components.
```
var $container = $('.scroll').infiniteScroll({
        // path is required, hack with {{#}}
       path: 'page{{#}}',
       loadOnScroll: false,
});

$container.on( 'scrollThreshold.infiniteScroll', function() {
          $container.append(_rows[1]);
})
```

But I got an error `TypeError: instance._init is not a function`. There are two many items in _rows. I just want to render it as the user scroll down. What should I do to make it work? Any assistance would be greatly appreciated.

**Comment by desandro** [comment]
Thank you for reporting this issue. I'm sorry to see you're having trouble with Infinite Scroll. Could you provide a **live URL**, or even better a **reduced test case**? See [Submitting Issues in the contributing guidelines](https://github.com/metafizzy/infinite-scroll/blob/master/.github/contributing.md#submitting-issues).

**Comment by sandronimus** [comment]
I have similar issue. In my case that caused by Select2. It has module named "InfiniteScroll" which conflicts with this plugin.

To reproduce issue try to add full version of Select2 and infinite-scroll on the same page.
After inifinite-scroll initialization you should see "Uncaught TypeError: instance._init is not a function" in browser console.

**Comment by grandecomplex** [comment]
I'm having this issue with Turbolinks. I load a page full page refresh on the page with Infinite Scroll. I click another link that uses Turbolinks. I click back in the browser. I get this error 

`TypeError: instance._init is not a function`

**Comment by grandecomplex** [comment]
I solved my problem. It was because you have to watch camel casing between old version of IS and the new v2. 

Old - $container.data("infinitescroll", null);

New - $container.data("infiniteScroll", null);

If you destroy something when page unloads via turbolinks, it needs to be fully deleted correctly or IS will look for older instances.

**Comment by desandro** [comment]
See #768

**Comment by josefarrugia** [comment]
@grandecomplex Cheers mate! This actually worked for me despite upgrade my version of InfiniteScroll.
