### ISSUE TITLE
Infinite Scroll v3 + Masonry 4.2.0 combination is not working ! 

### ISSUE THREAD

**Issue by archimj03** [metafizzy/infinite-scroll#754]
Demo : https://codepen.io/archimj03/pen/ZvawXo

I'm trying to make photo grid from -- Infinite Scroll v3 + Masonry 4.2.0 + Bootstrap 4 Beta 3

I'm trying to setup it from last 3 days and still it is not working please guide what's wrong with the code ??

I have copied code from example https://codepen.io/desandro/pen/eRRQVo and trying to add Bootstrap into it.

but when I try to use code in my website setup and remove "Codepen Slug" it stop working and do not show loader on page end. and also image grid look only 1 col grid which should be 2 col image grid as per Bootstrap.

1. kindly help me how to make loader image working on my website

2. how to make grid look proper 2 col-6 grid

**Comment by desandro** [comment]
Okay!

For Masonry and Bootstrap, the issue was that the `grid__gutter-sizer` was not being set, so it was 100% width, thus making the grid one column. Bootstrap uses padding/margin for its gutters, so you do not need to set `gutter` for Masonry.  See [Masonry + Bootstrap](https://masonry.desandro.com/extras.html#bootstrap)

See demo: https://codepen.io/desandro/pen/5628fed5c2b638912225b9844efd5dbc/?editors=1010

For Infinite Scroll, the only piece that I believe you're missing is an anchor link pointing to the next page. Something like:

``` html
<a class="pagination__next" href="/page/2">Next page</a>
```

If you have that, Infinite Scroll should be able to load `/page/2` on the site. See [docs on path](https://infinite-scroll.com/options.html#path)
