### ISSUE TITLE
Prevent more page from being loaded

### ISSUE THREAD

**Issue by otterslide** [metafizzy/infinite-scroll#778]
After 10 pages are loaded, I want to stop loading any further pages.
I can't figure out how I can disable infinite scroll.

If I use a custom getPath function that would work by returning null, but I want to use the default ".pagination__next".
Any way I can define a maximum pages to load before stopping?

**Comment by desandro** [comment]
You can use the similar behavior to [Scroll 2 pages, then load with button](https://infinite-scroll.com/extras.html#scroll-2-pages-then-load-with-button)

``` js
var $container = $('.container').infiniteScroll({
  // options...
});

// get Infinite Scroll instance
var infScroll = $container.data('infiniteScroll');

$container.on( 'load.infiniteScroll', onPageLoad );

function onPageLoad() {
  if ( infScroll.loadCount == 10 ) {
    // after 2nd page loaded
    // disable loading on scroll
    $container.infiniteScroll( 'option', {
      loadOnScroll: false,
    });
    // remove event listener
    $container.off( 'load.infiniteScroll', onPageLoad );
  }
}
```

You could also completely disable Infinite Scroll with the [`destroy` method](https://infinite-scroll.com/api.html#destroy) instead of setting `loadOnScroll` option

**Comment by otterslide** [comment]
Great, thanks!

**Comment by wakjoko** [comment]
hey, found that you could also stop loading next page with

`$container.data('infiniteScroll').canLoad = false;`

this should be mentioned in the docs i suppose
