### ISSUE TITLE
Custom append function with the history (that is not same to the path) and back button?

### ISSUE THREAD

**Issue by runnickrun** [metafizzy/infinite-scroll#821]
Hey, I'm trying to achieve some non-standard functionality here. 

So I have a WordPress website that has path something like `example.org/page/2`. 
I'm also using a custom append function to do some animations on appended content. 

But when I hit back button (e.g. moving from /page/3 to /page/2) it loads a regular WordPress page rather than page with the Infinite Scroll.  

Here is the video showing the process: http://recordit.co/PQ6r8nnYC9

So tried to use custom history path as per your last comment [https://github.com/metafizzy/infinite-scroll/issues/681#issuecomment-321834421](url) 
but it breaks back button functionality as InfiniteScroll doesn't read custom history and load the correct position. 

Is it possible to use custom history url while retaining back button functionality?

Hopefully that makes sense.

**Comment by desandro** [comment]
> It loads a regular WordPress page rather than page with the Infinite Scroll

That's because once you've moved to a different URL, like an article permalink, the 'page with Infinite Scroll' no longer exists since it was dynamically changed with JS. If you wish to maintain that page, you'll have to use a more powerful framework like React/Angular/Vue that manages entire page state in JS.

**Comment by runnickrun** [comment]
Yes, makes sense. Though I thought that using url scheme different than default WP one would make infinite scroll load sections via ajax on back button and then scroll to the latest scroll position. So that's   not possible, right?

**Comment by desandro** [comment]
> So that's not possible, right?

Well, it's not _impossible_, but there is no ready-made API built into Infinite Scroll for this behavior. It would require keeping track of scroll position & loaded pages across page loads. It could be done with URL parameters or cookies or other cross-page features. Like I said, frameworks are better designs for this kind of behavior.

The one proposal I do know of is [Screw Hashbangs: Building the Ultimate Infinite Scroll](https://tumbledry.org/2011/05/12/screw_hashbangs_building), from 2011, and appears more to be a proof of concept than a production-ready solution.

**Comment by ajmicek** [comment]
Hello, I'm the guy who wrote that infinite scroll thing back in 2011.
You actually get the scroll position for free, no local storage or cookies required, as long as you're able to do two parts:
• JS updates the URL when scrolling reaches bottom of the page so that the URL reflects what is being shown on that page. E.g. /page/1-2/ updates to /page/1-3/
• Your CMS/framework/whatever understands those URLs such that the XHTML output when visiting /page/1-3/ is identical to what the user sees when scrolling through three pages of content...

**Comment by aminta** [comment]
Hi @ajmicek , this is very important for me, can you give me an example?

I'm using Wordpress..

Thanks!

**Comment by desandro** [comment]
Infinite Scroll v3 will not support this feature. Closing here.

**Comment by ADTC** [comment]
I'm looking for this as well. Why is it closed as unsupported? I envision it something like this:
```
path: "/page/{{#}}",
history: "replace", // or: "push"
historyPath: "#page{{#}}", // <---- this could define how paths should be written and read in history
```
This way, even if the additional content is loaded from `www.example.com/page/5` the history will show `www.example.com/#page5` and upon _back_ navigation, Infinite Scroll could automatically scroll over to page 5 (loading all pages in between).

Is it possible to do this? I can't simply install a "more powerful framework" just to achieve this.
